# -*- coding: utf-8 -*-
"""Traditional_ML_plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ST9PudXyHvX5UzogkQRu53DQuuizJeK
"""

import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

#import of approaches results
path = os.getcwd() + "\\results"
results_1 = pd.read_csv(path + "\\approach_1_results.csv", index_col=0)
results_1["set"] = "test"
results_2 = pd.read_csv(path + "\\approach_2_results.csv", index_col=0)
results_3 = pd.read_csv(path + "\\approach_3_results.csv", index_col=0)
results = pd.concat([results_1, results_2, results_3], ignore_index=True, axis=0)


print(results.shape)
print(results.head())
print(results.columns)

for d in results["df"].unique():
  for m in ["recall", "precision", "f2_score"]: #for every metric

    y = results.loc[results["df"] == d, ["model" , m]]

    #plot
        
    sns.set(rc = {'figure.figsize':(15,5)})
    plt.figure()
    sns.boxplot(data=y, x="model", y=m, linewidth=2.5).set(title=d)
    plt.show()
