# -*- coding: utf-8 -*-
"""Methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13MaxwXJGiO-BXfKZnUojFKuwgV4bozad

This file contains methods for the "Data Import" file. 
In order to be correctly used, this file needs to be inside a Drive folder with the .py extension.
"""

from nltk.tokenize import regexp_tokenize
import re





