# -*- coding: utf-8 -*-
"""Traditional_ML_plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ST9PudXyHvX5UzogkQRu53DQuuizJeK
"""

import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

#import of ml results
path = os.getcwd() + "\\results"
results = pd.read_csv(path + "/approach_1_results.csv")

print(results.shape)

print(results.head())
print(results.columns)

for d in results["df"].unique():
  for m in ["recall", "precision", "f2_score"]: #for every metric

    y = results.loc[results["df"] == d, ["model" , m]]

    #plot
        
    sns.set(rc = {'figure.figsize':(15,5)})
    plt.figure()
    sns.boxplot(data=y, x="model", y=m, linewidth=2.5).set(title=d)
    plt.show()
